### ISSUE TITLE
A new way to import and start Socket IO 

### ISSUE THREAD

**Issue by nicolasjuan** [jschroeter/livephotoslideshow#1]
In line 5 of _server.js_ a little change make it work (with the newer versions of the libraries):
**from** -> const io = require('socket.io').listen(server); 
**to** -> const io = require('socket.io')(server);

Thank you for this app, was very useful to me.

**Comment by jschroeter** [comment]
Thanks for the input and glad it was useful to you! I (finally) updated the deps.
